### ISSUE TITLE
Copy nsec offline?

### ISSUE THREAD

**Issue by suddenwhipvapor** [lnbits/nostr-signing-device#17]
I was all happy to see an offline signing device for nostr apparently similar to seedsigner, yet I believe it is an extreme point of failure that you have to use an online website to copy the nsec onto the device... the point of using an offline signer is that you don't input your nsec in any online device, but you do it first thing, on a website even, when you configure the signer.
Thinking of the nsec as bitcoin wallet seed (it might be one, in the future), I would never setup a signer, only to input the nsec on a online website.

Is there any documented way to copy the nsec to the device from an offline laptop?

**Comment by motorina0** [comment]
On this folder you can find the installer app: https://github.com/lnbits/nostr-signing-device/tree/main/installer

This is a simple web app that you can run locally (offline).

For even more privacy you can compile the Arduino code and flash it yourself from the Arduino IDE.

See the hardware-wallet readme for more details: https://github.com/lnbits/hardware-wallet?tab=readme-ov-file#manual-install-instructions-without-webinstaller
